command:
  - streamlit
  - run
  - app.py

env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"

  - name: DEV_E2E_JOB_ID
    valueFrom: dev-e2e-job

  - name: STAGING_E2E_JOB_ID
    valueFrom: staging-e2e-job

  - name: PROD_E2E_JOB_ID
    valueFrom: prod-e2e-job

  - name: DEV_QA_JOB_ID
    valueFrom: dev-qa-job

  - name: STAGING_QA_JOB_ID
    valueFrom: staging-qa-job

  - name: PROD_QA_JOB_ID
    valueFrom: prod-qa-job

  - name: DEFAULT_ENVIRONMENT
    value: "PROD"
