datasets:

  erp:

    customers:
      path: erp/customers
      format: csv
      ingestion: autoloader
      ingestion_alert_threshold_percent: 1

    products:
      path: erp/products
      format: csv
      ingestion: autoloader
      ingestion_alert_threshold_percent: 1

    orders:
      path: erp/orders
      format: csv
      ingestion: autoloader
      ingestion_alert_threshold_percent: 1

  ecommerce:

    clickstream:
      path: ecommerce/clickstream
      format: csv
      ingestion: autoloader
      ingestion_alert_threshold_percent: 1

    returns:
      path: ecommerce/returns
      format: csv
      ingestion: autoloader
      ingestion_alert_threshold_percent: 1

  marketing:

    promotions:
      path: marketing/promotions
      format: csv
      ingestion: batch
      ingestion_alert_threshold_percent: 1